{
	TFile * f = new TFile("run.eff.root");
	TTree * t = (TTree*) f->Get("t");
	double runNo;
	double efftx1c1;
	double effty1c1;
	double effp3s1;
	double effp3c1;
	double effp2s1;
	double effp2c1;
	double effty2c1;
	double efftx2c1;
	double efftx1c2;
	double effty1c2;
	double effp3s2;
	double effp3c2;
	double effp2s2;
	double effp2c2;
	double effty2c2;
	double efftx2c2;
	double grade;
	double HVTXY1;
	double HVTXY2;
	double HVP3;
	double HVP2;
	double THRTXY1;
	double THRTXY2;
	double THRP3;
	double THRP2;
	t->SetBranchAddress("runNo",&runNo);
	t->SetBranchAddress("efftx1c1",&efftx1c1);	
	t->SetBranchAddress("effty1c1",&effty1c1);
	t->SetBranchAddress("effp3s1",&effp3s1);
	t->SetBranchAddress("effp3c1",&effp3c1);
	t->SetBranchAddress("effp2s1",&effp2s1);
	t->SetBranchAddress("effp2c1",&effp2c1);
	t->SetBranchAddress("effty2c1",&effty2c1);
	t->SetBranchAddress("efftx2c1",&efftx2c1);
	t->SetBranchAddress("efftx1c2",&efftx1c2);
	t->SetBranchAddress("effty1c2",&effty1c2);
	t->SetBranchAddress("effp3s2",&effp3s2);
	t->SetBranchAddress("effp3c2",&effp3c2);
	t->SetBranchAddress("effp2s2",&effp2s2);
	t->SetBranchAddress("effp2c2",&effp2c2);
	t->SetBranchAddress("effty2c2",&effty2c2);
	t->SetBranchAddress("efftx2c2",&efftx2c2);
	t->SetBranchAddress("grade",&grade);
	t->SetBranchAddress("HVTXY1",&HVTXY1);
	t->SetBranchAddress("HVTXY2",&HVTXY2);
	t->SetBranchAddress("HVP3",&HVP3);
	t->SetBranchAddress("HVP2",&HVP2);
	t->SetBranchAddress("THRTXY1",&THRTXY1);
	t->SetBranchAddress("THRTXY2",&THRTXY2);
	t->SetBranchAddress("THRP3",&THRP3);
	t->SetBranchAddress("THRP2",&THRP2);
	double HVmax = -1;
	double HVmin = 1e9;
	double THRmax = -1;
	double THRmin = 1e9;
	double runNomin = 1e9;
	double runNomax = -1;
	for (int i = 0; i<t->GetEntries(); i++){
		t->GetEntry(i);
		if (grade==10) continue;
		if (HVTXY1>HVmax) HVmax = HVTXY1;
		if (HVTXY2>HVmax) HVmax = HVTXY2;
		if (HVP3>HVmax) HVmax = HVP3;
		if (HVP2>HVmax) HVmax = HVP2;
		if (HVTXY1<HVmin) HVmin = HVTXY1;
		if (HVTXY2<HVmin) HVmin = HVTXY2;
		if (HVP3<HVmin) HVmin = HVP3;
		if (HVP2<HVmin) HVmin = HVP2;
		if (THRTXY1>THRmax) THRmax = THRTXY1;
		if (THRTXY2>THRmax) THRmax = THRTXY2;
		if (THRP3>THRmax) THRmax = THRP3;
		if (THRP2>THRmax) THRmax = THRP2;
		if (THRTXY1<THRmin) THRmin = THRTXY1;
		if (THRTXY2<THRmin) THRmin = THRTXY2;
		if (THRP3<THRmin) THRmin = THRP3;
		if (THRP2<THRmin) THRmin = THRP2;
		if (runNomax<runNo) runNomax=runNo;
		if (runNomin>runNo) runNomin=runNo;
	}
	if (THRmin==THRmax) THRmin-=1e-4;
	if (HVmin==HVmax) HVmin-=1e-4;

	TCanvas * c = new TCanvas("c","c",1440,960);
	TPad * p1 = new TPad("p1","p1",0,0.5,0.5,1);
	TPad * p2 = new TPad("p2","p2",0.5,0.5,1,1);
	TPad * p3 = new TPad("p3","p3",0,0,0.5,0.5);
	TPad * p4 = new TPad("p4","p4",0.5,0,1,0.5);
	p1->Draw();
	p2->Draw();
	p3->Draw();
	p4->Draw();

	printf("%lf->%lf\n",runNomin,runNomax);
	TH2D * h1 = new TH2D("h1","Efficiency of Tracker 1",1024,runNomin-1,runNomax+1,1024,0,1.1);
	h1->GetXaxis()->SetTitle("run#");
	TH2D * h2 = new TH2D("h2","Efficiency of Proto Type 3",1024,runNomin-1,runNomax+1,1024,0,1.1);
	h2->GetXaxis()->SetTitle("run#");
	TH2D * h3 = new TH2D("h3","Efficiency of Tracker 2",1024,runNomin-1,runNomax+1,1024,0,1.1);
	h3->GetXaxis()->SetTitle("run#");
	TH2D * h4 = new TH2D("h4","Efficiency of Proto Type 2",1024,runNomin-1,runNomax+1,1024,0,1.1);
	h4->GetXaxis()->SetTitle("run#");

	TString cut = "grade!=10&&efftx1c1!=-1";

	gStyle->SetOptStat(0);

	// TXY1
	p1->cd();
	h1->Draw();
	t->SetLineColor(kBlue);
	t->SetMarkerColor(kBlue);
	t->SetMarkerStyle(7);
	t->SetLineWidth(1);
	t->SetLineStyle(1);
	t->Draw("efftx1c1:runNo>>h11",cut,"SAMELP");
	t->SetLineColor(kRed);
	t->SetMarkerColor(kRed);
	t->SetMarkerStyle(7);
	t->SetLineWidth(1);
	t->SetLineStyle(1);
	t->Draw("effty1c1:runNo>>h12",cut,"SAMELP");
	t->SetLineColor(kMagenta);
	t->SetMarkerColor(kMagenta);
	t->SetMarkerStyle(1);
	t->SetLineWidth(3);
	t->SetLineStyle(2);
	t->Draw(Form("(HVTXY1-%lf)/%lf:runNo>>h13",HVmin*1.1-HVmax*0.1,(HVmax-HVmin)*1.2),cut,"SAMELP");
	t->SetLineColor(kGreen);
	t->SetMarkerColor(kGreen);
	t->SetMarkerStyle(1);
	t->SetLineWidth(3);
	t->SetLineStyle(2);
	t->Draw(Form("(THRTXY1-%lf)/%lf:runNo>>h14",THRmin*1.1-THRmax*0.1,(THRmax-THRmin)*1.2),cut,"SAMELP");
	TLegend * legend = new TLegend(0.11,0.11,0.4,0.3);
	legend->AddEntry(h11,"Efficiency of TrackerX Wire#0");
	legend->AddEntry(h12,"Efficiency of TrackerY Wire#0");
	legend->AddEntry(h13,"HV on TrackerXY");
	legend->AddEntry(h14,"Threshold on TrackerXY");
	legend->SetLineColor(0);
	legend->SetFillStyle(0);
	legend->Draw("SAME");

	// TXY2
	p3->cd();
	h3->Draw();
	t->SetLineColor(kBlue);
	t->SetMarkerColor(kBlue);
	t->SetMarkerStyle(7);
	t->SetLineWidth(1);
	t->SetLineStyle(1);
	t->Draw("efftx2c1:runNo",cut,"SAMELP");
	t->SetLineColor(kRed);
	t->SetMarkerColor(kRed);
	t->SetMarkerStyle(7);
	t->SetLineWidth(1);
	t->SetLineStyle(1);
	t->Draw("effty2c1:runNo",cut,"SAMELP");
	t->SetLineColor(kMagenta);
	t->SetMarkerColor(kMagenta);
	t->SetMarkerStyle(1);
	t->SetLineWidth(3);
	t->SetLineStyle(2);
	t->Draw(Form("(HVTXY2-%lf)/%lf:runNo",HVmin*1.1-HVmax*0.1,(HVmax-HVmin)*1.2),cut,"SAMELP");
	t->SetLineColor(kGreen);
	t->SetMarkerColor(kGreen);
	t->SetMarkerStyle(1);
	t->SetLineWidth(3);
	t->SetLineStyle(2);
	t->Draw(Form("(THRTXY2-%lf)/%lf:runNo",THRmin*1.1-THRmax*0.1,(THRmax-THRmin)*1.2),cut,"SAMELP");

	// P3
	p2->cd();
	h2->Draw();
	t->SetLineColor(kBlue);
	t->SetMarkerColor(kBlue);
	t->SetMarkerStyle(7);
	t->SetLineWidth(1);
	t->SetLineStyle(1);
	t->Draw("effp3s1:runNo>>h21",cut,"SAMELP");
	t->SetLineColor(kRed);
	t->SetMarkerColor(kRed);
	t->SetMarkerStyle(7);
	t->SetLineWidth(1);
	t->SetLineStyle(1);
	t->Draw("effp3c1:runNo>>h22",cut,"SAMELP");
	t->SetLineColor(kMagenta);
	t->SetMarkerColor(kMagenta);
	t->SetMarkerStyle(1);
	t->SetLineWidth(3);
	t->SetLineStyle(2);
	t->Draw(Form("(HVP3-%lf)/%lf:runNo>>h23",HVmin*1.1-HVmax*0.1,(HVmax-HVmin)*1.2),cut,"SAMELP");
	t->SetLineColor(kGreen);
	t->SetMarkerColor(kGreen);
	t->SetMarkerStyle(1);
	t->SetLineWidth(3);
	t->SetLineStyle(2);
	t->Draw(Form("(THRP3-%lf)/%lf:runNo>>h24",THRmin*1.1-THRmax*0.1,(THRmax-THRmin)*1.2),cut,"SAMELP");
	legend = new TLegend(0.11,0.71,0.4,0.89);
	legend->AddEntry(h21,"Efficiency of Chamber Corner Wire(#20)");
	legend->AddEntry(h22,"Efficiency of Chamber Center Wire(#13)");
	legend->AddEntry(h23,"HV on Chamber");
	legend->AddEntry(h24,"Threshold on Chamber");
	legend->SetLineColor(0);
	legend->SetFillStyle(0);
	legend->Draw("SAME");

	// P2
	p4->cd();
	h4->Draw();
	t->SetLineColor(kBlue);
	t->SetMarkerColor(kBlue);
	t->SetMarkerStyle(7);
	t->SetLineWidth(1);
	t->SetLineStyle(1);
	t->Draw("effp2s1:runNo",cut,"SAMELP");
	t->SetLineColor(kRed);
	t->SetMarkerColor(kRed);
	t->SetMarkerStyle(7);
	t->SetLineWidth(1);
	t->SetLineStyle(1);
	t->Draw("effp2c1:runNo",cut,"SAMELP");
	t->SetLineColor(kMagenta);
	t->SetMarkerColor(kMagenta);
	t->SetMarkerStyle(1);
	t->SetLineWidth(3);
	t->SetLineStyle(2);
	t->Draw(Form("(HVP2-%lf)/%lf:runNo",HVmin*1.1-HVmax*0.1,(HVmax-HVmin)*1.2),cut,"SAMELP");
	t->SetLineColor(kGreen);
	t->SetMarkerColor(kGreen);
	t->SetMarkerStyle(1);
	t->SetLineWidth(3);
	t->SetLineStyle(2);
	t->Draw(Form("(THRP2-%lf)/%lf:runNo",THRmin*1.1-THRmax*0.1,(THRmax-THRmin)*1.2),cut,"SAMELP");
}
